trainer:
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: ./
      name: logs
      default_hp_metric: false
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: validation/iou
        mode: max
        save_last: true
model:
  in_channels: 1
  out_channels: 3
  init_features: 32
  learning_rate: 0.001
data:
  root_dir: ./data/
